import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/layout/sidenav";
import Header from "@/components/layout/header";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} antialiased`}>
        <Header />
        <div className="flex w-full">
          <SideNav className="sticky top-20 shrink-0 h-[calc(100vh-5rem)]" />
          <main className="grow">{children}</main>
        </div>
        <div id="modal-root" />
      </body>
    </html>
  );
}
